volta-cli/website

- subdomains/docs/_advanced/hooks.md
- subdomains/docs/_data/sidebar.yml
There was already an "Advanced" section, however it was hidden in the sidebar. I uncommented it so that the sidebar section would exist, and added docs for Hooks.
[Rendered](https://github.com/charlespierce/website/blob/docs_for_hooks/subdomains/docs/_advanced/hooks.md) (Note: The `{% raw %}` and `{% endraw %}` are Liquid template helpers to prevent the `{{os}}` blocks from being replaced by an empty string, since they are the same format that Liquid uses for templating)
> Add docs for hooks to advanced section

- subdomains/docs/_contributing/index.md
The `volta-install.sh` script can build and install `dev` and `release` builds of Volta. This new workflow is only one command, and is closer to how users will install Volta now that `volta-install.sh` is served from http://get.volta.sh.
> Updated commands to build and install Volta locally

- subdomains/docs/_guide/getting-started.md
Closes volta-cli/volta#462
Update the "Getting Started" page to correctly reflect all of the shells that we auto-configure, and remove the warning about the installer being bash-focused.
> Update installation instructions to include all auto-configured shells

- subdomains/docs/_guide/getting-started.md
- subdomains/www/index.md
Related to https://github.com/volta-cli/get/pull/3
Once we convert the `get.volta.sh` domain into a 200 proxy, we can remove the curl flags from our installation directions, as they won't be needed any more.
Note: I left the callouts in the blog posts alone, as I felt the blog posts should remain as-is, instead of trying to keep them up-to-date with the current recommended approach.
> Remove curl flags from installer CTAs

- subdomains/docs/_guide/getting-started.md
- theme/_includes/note.html
- theme/_includes/warn.html
- theme/_sass/volta/_alerts.scss
While debugging an issue on Discord, we discovered that `volta install <package>` only works on Windows if developer mode is on (or if you are running an administrative prompt), because the Windows API to create a symlink requires one of those two situations.
We don't currently have a good solution to make it work without Developer Mode, so adding a note to the "Getting Started" page that lets the user know developer mode is required to get full functionality from Volta.
Also restructured some of the theme CSS and added a `note.html` snippet that can be used to insert a note into a page (similar to a warning but colored teal instead of yellow and titled "NOTE" instead of "WARNING").
> Add note about needing Developer Mode to Windows section

- subdomains/docs/_guide/getting-started.md
Based on some feedback we have received about the Getting Started guide, clean up 2 things:
1. Add a "Windows Subsystem for Linux" section to make it explicit that WSL users should follow the Unix install guide.
2. Clean up the note about needing Developer Mode / Elevated Privileges to make it clear that we recommend Developer Mode and Elevated Privileges is not recommended.
> Add WSL section and clean up Windows requirement note

- subdomains/docs/_contributing/index.md
Per comments on volta-cli/volta#505, changes made while refactoring the resolve/fetch/install process require Rust v1.34.0+ to build.
> Bump required Rust version to 1.34 in Contributing.

- subdomains/docs/_data/sidebar.yml
- subdomains/docs/_reference/index.md
- subdomains/docs/_reference/list.md
- Add basic documentation for `install`, including a warning about the state of `--format=human`.
- Update the output shown for `volta` itself to match what it currently shows, including the newly added `list` command.
> Add install docs, update index docs.

- subdomains/docs/_guide/getting-started.md
Our "Getting Started" docs, under the section about how to manually edit the terminal startup scripts, were suggesting that users set `VOLTA_HOME` to `~/.volta`. However, if a user actually does that, it will subtly break Volta since we don't automatically expand `~` into the user's home directory.
This can lead to the creation of a bunch of directories named `~` everywhere the user runs `volta`, as well as breaking `yarn` scripts since the `PATH` isn't expanded there either.
> Fix manual editing of console startup scripts

- subdomains/docs/_advanced/packages.md
- subdomains/docs/_data/sidebar.yml
- subdomains/docs/_guide/understanding.md
Add some more Advanced docs about specifics of the package install process. Also update the "Understanding Volta" section about installing packages to link to that for more information.
Note: This shouldn't be merged until Volta 0.6.8 is released, as it references changes in that version which aren't available yet.
> Add advanced section with more information about installing packages

- subdomains/docs/_advanced/installers.md
- subdomains/docs/_data/sidebar.yml
- subdomains/docs/_guide/getting-started.md
- subdomains/docs/_reference/fetch.md
- subdomains/docs/_reference/help.md
- subdomains/docs/_reference/index.md
- subdomains/docs/_reference/install.md
- subdomains/docs/_reference/pin.md
- subdomains/docs/_reference/setup.md
* Added "Reference" page for `volta setup`, with information about how it modifies the user's machine to support Volta
* Updated other "Reference" pages to show the current output of `volta help <command>` (several were outdated).
* Reworked the "Installers" Advanced page to link to the `volta setup` reference page.
* Added a note about how to run the installer without `volta setup`
* Added a link to the above note to the "Getting Started" page, so it's more discoverable for users that want that behavior.
> Add docs for 'volta setup'

- theme/_includes/footer.html
- theme/_sass/volta/_layout.scss
- rename "The Volta Contributors" to "the Volta community" -- feels more warm and inclusive, defines Volta more as a community than as a recipient of donations
- narrow the horizontal padding on mobile to avoid the :zap: spilling over
- widen the vertical gap between footer sections (it was crowding)
[Preview](https://5e63f73ba05d370008074912--pensive-ardinghelli-58fa3b.netlify.com)
> Tweaks to footer

- theme/_layouts/post.html
I saw a post about Volta today (https://blog.volta.sh/2020/07/23/declare-your-tools/) on my phone and tried to click the hamburger menu in order to read more about the project, and noticed it is broken. This is easily reproducible using browser dev tools: the menu does not work within a specific blog post, but does within the directory of blog posts (https://blog.volta.sh/). It looks like it's because there is no `nav.sidebar` from within a given blog post. 
This PR adds the sidebar to a blog post to fix this behavior. 🙂 
Blog listing (with functionality):
Blog post (no `nav.sidebar`, so functionality does not work):
> Include sidebar.html within blog post

- subdomains/docs/_advanced/uninstall.md
- subdomains/docs/_data/sidebar.yml
We've had an outstanding issue for a while to document the steps needed to uninstall Volta (https://github.com/volta-cli/volta/issues/531). Adding a section under `Advanced` as, at least on Unix, it's a little bit involved.
> Add Advanced section about Uninstalling Volta

- subdomains/docs/_data/sidebar.yml
- subdomains/docs/_reference/completions.md
- subdomains/docs/_reference/uninstall.md
- subdomains/docs/_reference/which.md
Noted in a comment (https://github.com/volta-cli/volta/issues/531#issuecomment-671045651), our "Reference" section is out-of-date and doesn't show a reference for all commands.
Updated to include all of the commands that are shown when you run `volta --help` and re-ordered to match the order of commands listed there.
> Update reference section with all commands

- subdomains/blog/_posts/2018-08-20-state-of-the-notion.md
- subdomains/blog/_posts/2019-02-05-state-of-the-notion.md
- subdomains/blog/_posts/2019-05-13-hello-volta.md
- theme/_sass/volta/_layout.scss
This PR adds notices to old blog posts clearing up any potential confusion about the 2019 rename (Notion -> Volta), following a discussion in volta-cli/volta#1013.
> Editor's notes about the project rename

- subdomains/docs/_guide/understanding.md
- Mention the option to use `volta fetch` to not change the default version. The verbosity will drive home that `volta install` will change your default _every_ time it is run.
> docs(guide): emphasize the install command is for setting a default version

- subdomains/docs/_guide/getting-started.md
Does it make sense to mention "macOS" in the Unix section? I feel like I typically expect guides to segment between Mac, Windows, and Linux, so I was expecting a Mac section as well.
> Mention 'macOS' in Unix section of 'Getting Started'

- subdomains/docs/_advanced/installers.md
Info
-----
* With the release of Volta 1.1.0, the get.volta.sh installer only works for that version, due to the change in release artifacts.
* We have a section in our docs about installing old versions, from the last time we had a breaking change in the install script (Volta 0.7.0).
* However, Volta 0.7.0 is 2.5 years old now (Volta 1.0.0 itself is almost 2 years old!) and far from supported.
* Rather than adding an extra section and trying to explain to use script A for Volta < 0.7.0 and script B for Volta between 0.7.0 and 1.1.0, we can likely drop the reference to the 0.6.8 installer entirely.
Changes
-----
* Updated the minimum supported Volta version for the default installer in the `Installing Old Versions`
* Update the code sample to use the appropriate 1.0 installer and example …
> Update 'Installing Old Versions' section with 1.1.0

- subdomains/docs/_advanced/pnpm.md
This tells users about removing the old `pnpm` package, which would become isolated after enabling the pnpm support.
> docs: Update pnpm migration note

- README.md
Current instructions result in error
```shell
~code/volta-website main
null.local ᐳ cd subdomains/www
~code/volta-website/subdomains/www main
null.local ᐳ bundle exec jekyll serve
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
```
> docs: improve usage instructions in README.md

- subdomains/docs/_advanced/installers.md
- subdomains/docs/_guide/getting-started.md
This PR aims to expand the documentation about manual installation and CI usage. As discussed in https://github.com/volta-cli/volta/issues/1389 some users may find it difficult to catch the fact volta requires `install` to be ran at least once before running any other tooling and a few users had no idea bout the provided Github action that solves the deterministic behaviour.
> Add more information to manual installation instructions

- subdomains/docs/_data/versions.json
While reviewing some docs updates, I noticed the example versions of Node & TypeScript are quite old. Bumping those to represent more recent versions.
> Bump versions file to represent more recent tool versions in docs.

- subdomains/docs/_advanced/uninstall.md
Hi,
Nice tool, thanks for creating this ! (Well, just starting to try it but so far looks very good to me :D)
It seems that `~/.zshenv` is one of the files modified by the install process (both noticed on my machine, and I can find refererences to it in the code), so, this PR updates the uninstall docs to reflect that fact.
> Add `.zshenv` to uninstall instructions
